global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "web"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "web"
    static_configs:
      - targets: [ "host.docker.internal:8002" ]