services:
  web:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: api-sql
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
    depends_on:
      - db
    networks:
      - db-net

  db:
    image: postgres:13-alpine
    container_name: db-sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
    networks:
      - db-net

networks:
  db-net:
    driver: bridge