services:
  web:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: api-logging
    command: |
      bash -c 'uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/
    ports:
      - "8001:8000"
    depends_on:
      - elasticsearch
    networks:
      - es-net

  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile-ES
    container_name: elasticsearch-logging
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./ci/data/es/db:/usr/share/elasticsearch/data
      - ./ci/data/es/logs:/usr/share/elasticsearch/logs
      - ./ci/data/es/repo:/usr/share/elasticsearch/repo
    expose:
      - 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - es-net

  kibana:
    container_name: kibana-logging
    image: docker.elastic.co/kibana/kibana:8.2.0
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  es-net:
    driver: bridge