services:
  simple-api:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: simple-api
    command: |
      bash -c 'uvicorn src.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/
    ports:
      - "8000:8000"
